name: Github Actions CI Pipeline

on:
  # a pipeline vai ser chamada quando for criado um PR pra master
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: build_game
    runs-on: ubuntu-latest
    
    container:
      image: pedrodm22/raylib_static_build:5.5
      volumes:
        - ${{ github.workspace }}:/app

    steps:
    - uses: actions/checkout@v4
    - name: make game 
      run: make game

  tests:
    name: build_and_run_unit_tests
    runs-on: ubuntu-latest

    container:
      image: pedrodm22/raylib_static_build:5.5
      volumes:
        - ${{ github.workspace }}:/app

    steps:
    - uses: actions/checkout@v4
    - name: make tests
      run: make tests